In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
from pathlib import Path

In [3]:

data_path = Path("../data/banana.csv")
df_banana = pd.read_csv(data_path)

In [4]:
df_banana.head()

V1     V2  Class
0  1.140 -0.114      1
1 -1.520 -1.150      2
2 -1.050  0.720      1
3 -0.916  0.397      2
4 -1.090  0.437      2

In [5]:
# expecting labels 1 and -1

# transform label 2 to -1
df_banana.loc[df_banana.Class == 2, 'Class'] = -1
df_banana.head()

V1     V2  Class
0  1.140 -0.114      1
1 -1.520 -1.150     -1
2 -1.050  0.720      1
3 -0.916  0.397     -1
4 -1.090  0.437     -1

In [6]:
feature_names = ['V1', 'V2']
x = df_banana[feature_names].to_numpy()

label_name = ['Class']
y = df_banana[label_name].to_numpy()

In [13]:
from jax import numpy as jnp
x = jnp.array(x)
y = jnp.array(y)

In [15]:
from tkm.model import fit
%time W, loss, error = fit(x,y)

CPU times: user 59.2 s, sys: 19 s, total: 1min 18s
Wall time: 39.3 s


In [12]:
loss

[DeviceArray([[1780.1318]], dtype=float32),
 DeviceArray([[8340.863]], dtype=float32),
 DeviceArray([[1678.4861]], dtype=float32),
 DeviceArray([[2477.993]], dtype=float32)]

In [10]:
error

[DeviceArray(0.19622642, dtype=float32),
 DeviceArray(0.30320755, dtype=float32),
 DeviceArray(0.14226416, dtype=float32),
 DeviceArray(0.10245283, dtype=float32)]

In [19]:
from tkm.model import predict

scores = predict(x, W)

In [20]:
scores.shape

(5300,)

In [21]:
scores

DeviceArray([ 0.11154461, -0.5162263 ,  0.35784817, ..., -0.23757172,
              0.9656782 , -1.2011389 ], dtype=float32)