In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import pandas as pd
from pathlib import Path

In [4]:
data_path = Path("../data/banana.csv")
df_banana = pd.read_csv(data_path)

In [5]:
df_banana.head()

V1     V2  Class
0  1.140 -0.114      1
1 -1.520 -1.150      2
2 -1.050  0.720      1
3 -0.916  0.397      2
4 -1.090  0.437      2

In [6]:
# expecting labels 1 and -1

# transform label 2 to -1
df_banana.loc[df_banana.Class == 2, 'Class'] = -1
df_banana.head()

V1     V2  Class
0  1.140 -0.114      1
1 -1.520 -1.150     -1
2 -1.050  0.720      1
3 -0.916  0.397     -1
4 -1.090  0.437     -1

In [7]:
feature_names = ['V1', 'V2']
x = df_banana[feature_names].to_numpy()

label_name = ['Class']
y = df_banana[label_name].to_numpy()

In [8]:
from jax import numpy as jnp
x = jnp.array(x)
y = jnp.array(y)

In [9]:
from jax import random
key = random.PRNGKey(42)

In [10]:
from tkm.model import init

# W, reg, Matd = init(key, x)

In [12]:
from tkm.model import fit

%timeit W = fit(key,x,y)

70.2 ms ± 1.34 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
from jax import jit

fit_compiled = jit(fit)

%time W = fit(key, x, y)

: 

In [19]:
loss

[DeviceArray([[1791.499]], dtype=float32),
 DeviceArray([[1791.499]], dtype=float32),
 DeviceArray([[1791.499]], dtype=float32),
 DeviceArray([[1791.499]], dtype=float32)]

In [20]:
error

[DeviceArray(0.10773585, dtype=float32),
 DeviceArray(0.10773585, dtype=float32),
 DeviceArray(0.10773585, dtype=float32),
 DeviceArray(0.10773585, dtype=float32)]

In [11]:
from tkm.model import predict

%time scores = predict(x, W)

CPU times: user 63.5 ms, sys: 2.41 ms, total: 65.9 ms
Wall time: 66 ms


In [12]:
scores.shape

(5300,)

In [21]:
scores

DeviceArray([ 0.11154461, -0.5162263 ,  0.35784817, ..., -0.23757172,
              0.9656782 , -1.2011389 ], dtype=float32)